---
title: "CAP Diffuse Glioma Subcommittee Notes"
author: "W. McDonald, MD"
date: "10/31/2018"
output:
  html_document:
    df_print: paged
  pdf_document: default
  word_document: default
csl: vancouver.csl
bibliography: bibliography.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Purpose: 

Associate the seven mutations/alterations in the CAP Diffuse Glioma subcommittee comprised of Harris, Hawks, and McDonald with appropriate references either 1) derived from the search, or 2) submitted by the subcommittee (for approval by the methodologist)

Note: I will supplement observations from the literature with searches of the TCGA database using [link](cbioportal.org) merged LGG and GBM datasets 
[@RN2358]

### Chromosome 10:
TCGA incidence:
GBM: 
LGG: 
Merged:

Chromosome 10 is requently lost in GBM. The identification of -10 or -10q would support higher "molecular grade," if found.

Collins 2014 RefID 371: 65% of GBM showed monosomy; 20% of GBM showed 10q partial deletion; only 11% of GBM showed no abnormality.
Dubbink 2016 RefID 449: 10q loss in 51 of 55 GBM
Fontana 2016 RefID 552: 10q loss in 75% (of 142) GBM
Houdova Megova 2017 RefID 769: 10p loss in 22/69 IDH WT GBM
Mott 2008 RefID 1391: monosomy 10 in 22.5% of n=120 GBM
Ramalho-Carvalho 2013 RefID 1656: monosomy 10 in 32/60 AA/GBM (n=60); 10q26.1 loss 68.3%

Note: cIMPACT-NOW update 3 (reference Brat Acta NP 2018) has already recommended testing for EGFR amplification, +7, -10 or TERT promoter

### Chromosome 7: 
TCGA incidence:
GBM:
LGG: 
Merged:


### BRAF:
TCGA incidence (BRAF V600E):
GBM:
LGG: 
Merged: 0.86% (5x V600E, 1x D594G, 1x V504_506 dup)


### Histone 3:
TCGA incidence:
GBM:
LGG: 
Merged:


### CDKN2A:
TCGA incidence:
GBM:
LGG: 
Merged: 57.09% deleted, 0.68% mutated


### CDK4: 
TCGA incidence:
GBM:
LGG: 
Merged: 14.36% amplified


### MDM2: 
TCGA incidence:
GBM:
LGG: 
Merged: 8.33% amplified

